### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by vko-online** [2gis/geoloc#4]
Эта библиотека используеться в веб версии 2GIS? 
Дело в том что у меня почему то определение местоположение очень долго (использую нативную), но на вашем сайте она очень быстрая, и интересно, вы используете что то другое или эту библиотеку?

**Comment by Riim** [comment]
Нет, в веб версии используется [HTML5 Geolocation](https://github.com/Leaflet/Leaflet/blob/81e71fe7e03aa252735f540d2e66af61ee6ce1a5/src/map/ext/Map.Geolocation.js#L34). В данной обёртке он используется как один из провайдеров.
